imports:
    - { resource: "services/forms.yml" }
    - { resource: "services/installer.yml" }

services:
    _defaults:
        public: true

    ### Registries
    process_manager.registry.processes:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - ProcessManagerBundle\Process\ProcessInterface
            - 'Process Manager Processes'

    process_manager.registry.process_reports:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - ProcessManagerBundle\Report\ReportInterface
            - 'Reports'

    process_manager.registry.process_handler_factories:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - ProcessManagerBundle\Monolog\HandlerFactoryInterface
            - 'Handler Factories'

    process_manager.form.registry.processes:
        class: CoreShop\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

    ### Processes
    process_manager.process.cli:
        class: ProcessManagerBundle\Process\Cli
        tags:
            - { name: process_manager.process, type: cli, form-type: ProcessManagerBundle\Form\Type\Processes\CliType }

    process_manager.process.pimcore:
        class: ProcessManagerBundle\Process\Pimcore
        tags:
            - { name: process_manager.process, type: pimcore, form-type: ProcessManagerBundle\Form\Type\Processes\PimcoreType }

    ### Event listeners
    process_manager.event_listener.artifact:
        class: ProcessManagerBundle\EventListener\ArtifactDeletionListener
        arguments:
            - '@process_manager.repository.process'
        tags:
            - { name: kernel.event_listener, event: pimcore.asset.postDelete, method: onArtifactAssetDelete }

    process_manager.event_listener.cron:
        class: ProcessManagerBundle\EventListener\CronListener
        tags:
            - { name: kernel.event_listener, event: pimcore.system.maintenance, method: run, arguments: }
        arguments:
            - '@process_manager.registry.processes'

    process_manager.logger:
        class: ProcessManagerBundle\Logger\ProcessLogger
        arguments:
            - '@logger'

    process_manager.monolog.processor:
        class: ProcessManagerBundle\Monolog\ProcessProcessor
        lazy: true
        arguments:
            - '@process_manager.default_handler_factory'
            - '@process_manager.registry.process_handler_factories'
        tags:
            - { name: monolog.processor }

    process_manager.monolog.handler:
        class: ProcessManagerBundle\Monolog\ProcessHandler

    process_manager.default_handler_factory:
        class: ProcessManagerBundle\Logger\DefaultHandlerFactory
        arguments:
            - '%kernel.logs_dir%'

    process_manager.default_report:
        class: ProcessManagerBundle\Report\DefaultReport

    ### Startup Resolver
    process_manager.registry.startup_form_resolver:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - ProcessManagerBundle\Process\ProcessStartupFormResolverInterface
            - 'Process Startup Form Resolver'

    process_manager.startup_resolver:
        class: ProcessManagerBundle\Process\CompositeProcessStartupFormResolver
        arguments:
            - '@process_manager.registry.startup_form_resolver'

    process_manager.run_manager:
        class: ProcessManagerBundle\Process\RunManager
        public: true
